blog/urls.py
from django.urls import path

from . import views

# アプリケーション名
app_name = 'blog'
urlpatterns = [
    # blog/''にアクセスされたらviews.pyのIndexViewを実行
    # ページ名はindex
    path('', views.IndexView.as_view(), name="index"),
    # blog/'post'にアクセスされたらviews.pyのPostViewを実行
    # ページ名はpost
    path('post', views.PostView.as_view(), name="post"),

    path('blog-list/', views.BlogListView.as_view(), name="blog_list"),
]

diary/urls.py
from django.urls import path

from . import views

# アプリケーション名
app_name = 'diary'
urlpatterns = [
    # ''にアクセスされたらviews.pyのIndexViewを実行
    # ページ名はindex
    path('', views.IndexView.as_view(), name="index"),

    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),

    path('diary-list/', views.DiaryListView.as_view(), name="diary_list"),
    # <int:pk>・・・URL引数　pkという名前でビューに渡される　int型に制限
    path('diary-detail/<int:pk>', views.DiaryDetailView.as_view(), name="diary_detail"),
    path('diary-create/', views.DiaryCreateView.as_view(), name="diary_create"),
    path('diary-update/<int:pk>', views.DiaryUpdateView.as_view(), name="diary_update"),
    path('diary-delete/<int:pk>', views.DiaryDeleteView.as_view(), name="diary_delete"),
]

private_diary/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    # ""にアクセスされたら、diary.urlsに振り分ける
    path("", include('diary.urls')),
    # "blog/"にアクセスされたら、diary.urlsに振り分ける
    path("blog/", include('blog.urls')),

    # "accounts/"にアクセスされたら、allauthの認証ページに振り分ける
    # ルーティング内容はP227を参照
    path("accounts/", include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL,
    document_root=settings_dev.MEDIA_ROOT)

diary/models.py
from accounts.models import CustomUser
from django.db import models


class Diary(models.Model):
    """日記モデル"""
    # 必要な項目を列挙する
    # ユーザー：外部キー（カスタムユーザー）
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    # タイトル：文字列　最大40文字
    title = models.CharField(verbose_name='タイトル', max_length=40)
    # 本文：テキスト　空白許可
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    # 写真：画像　空白許可
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    # 作成日時：日付時刻　新規作成時、自動で現在時刻を設定
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    # 更新日時：日付時刻　更新時、自動で現在時刻を設定
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = '日記'

    # オブジェクトの文字列表現
    # 管理サイトでの簡易表示用
    def __str__(self):
        return self.title + "(" + self.content[:10] + "...)"

diary/forms.py
import os

from django import forms
from django.core.mail import EmailMessage

from .models import Diary

# お問い合わせ内容を入力するフォーム
class InquiryForm(forms.Form):
    # 入力する内容
    # CharField:<input type='text'>
    # EmailField:<input type='email'>
    # label:表示する名称
    # 詳細はテキストP.47
    name = forms.CharField(label='NAME', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    # コンストラクタ
    # 各入力フィールドの属性を設定
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # nameのclass属性にform-controlを設定
        self.fields['name'].widget.attrs['class'] = 'form-control'
        # nameのplaceholder属性に文字列を設定
        self.fields['name'].widget.attrs['placeholder'] = 'Input Name.'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    # 入力内容をもとにメール送信処理を行うメソッド
    def send_email(self):
        # cleaned_dataからエラー処理完了後の入力データを取得
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

# 日記の内容を入力するフォーム
# ModelForm：モデルへの入力するためのフォーム
class DiaryCreateForm(forms.ModelForm):
    class Meta:
        # 対象モデルを指定
        model = Diary
        # 入力する項目を指定
        fields = ('title', 'content', 'photo1', 'photo2', 'photo3',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for文を使って全項目に同じクラス属性を設定
        # IquiryFormと同じように個別に設定するのがベスト
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

diary/views.py
import logging

from django.urls import reverse_lazy

from django.views import generic

from django.contrib import messages

from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin

# 同じフォルダのforms.pyからInquiryFormクラスをインポート
from .forms import *

from .models import Diary

from .mixins import OnlyYouMixin

logger=logging.getLogger(__name__)

# indexページを表示するための処理
# TempateView：HTMLを表示する為のクラス
class IndexView(generic.TemplateView):
    # 表示したいHTMLを指定
    template_name="index.html"

# inquiryページを表示するための処理
# FormView：フォームを使ったページを表示するためのクラス
# LoginRequieredMix：ログインしていなければ見られないページ
class InquiryView(generic.FormView):
    template_name="inquiry3.html"
    # 表示したいフォーム
    form_class=InquiryForm
    # 送信が成功したときに移動するURL
    # reverse_lazy:URLの逆引きを行う関数
    # 　diaryアプリのinquiryページのURLを取得
    success_url=reverse_lazy('diary:inquiry')

    # 送信が成功したときに行う処理
    # 引数formに入力した内容が格納される
    def form_valid(self, form):
        # form(InquiryFormクラス)のsend_emailメソッドを実行
        form.send_email()

        # success_urlページで表示するメッセージ
        messages.success(self.request, 'メッセージを送信しました')

        # form.cleand_data['フィールド名']にはエラー処理が完了したデータ保存されている
        logger.info('Inquriry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

# 日記一覧ページを表示するビュー
# ListView：指定したモデルを一覧表示する為のクラス
class DiaryListView(LoginRequiredMixin, generic.ListView):
    # 一覧表示したいモデルを指定
    model = Diary
    template_name = 'diary_list.html'
    # １ページに表示する件数を指定
    paginate_by = 2

    # get_queryset：表示したいモデルを設定するメソッド
    # これがないと、モデルの全データが出力される
    def get_queryset(self):
        # モデル.objects：モデルの全データにアクセスする
        # .filter：検索条件を指定
        # self.request.user：ログインしているユーザー
        # .order_by：出力順を指定　フィールド名の先頭に「-」で降順
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

# 日記を１件表示するビュー
# DetailView：指定したモデルに対して、URL引数pkで受け取った主キーを持つデータを表示するクラス
class DiaryDetailView(LoginRequiredMixin, OnlyYouMixin, generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'

# 日記の新規登録をするビュー
# CreateView：指定したモデルに対して、指定したフォームで入力されたデータを登録するクラス
# 　　　　　　　だいたいFormViewと同じ
class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    # データの入力に使用するフォーム
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary_list')

    # 入力が正しいときに行う処理（データベースに保存する処理）
    def form_valid(self, form):
        # フォームに入力された内容を一時保存する
        # commit=False・・・データベースにはまだ保存されない
        diary = form.save(commit=False)
        # user項目はログインしているユーザーを直接設定
        diary.user = self.request.user
        # データベースに保存
        diary.save()

        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    # 入力が正しくなかった時の処理
    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました。")
        return super().form_invalid(form)

# 日記を更新するビュー
# UpdateView：指定したモデルの、URL引数pkで受け取った主キーを持つデータに対して、
# 　　　　　　　指定したフォームで入力されたデータで更新するクラス
# 　　　　　　　だいたいCreateViewと同じ
class DiaryUpdateView(LoginRequiredMixin, OnlyYouMixin, generic.UpdateView):
    model = Diary
    template_name = 'diary_update.html'
    # 今回は「たまたま」新規作成時と同じ入力内容なのでDiaryCreateForm
    form_class = DiaryCreateForm

    # 成功時の移動先が固定でない為
    # success_urlの代わりにget_sccess_urlメソッドを使う
    def get_success_url(self):
        # URL引数としてkwargsに値を設定する
        return reverse_lazy('diary:diary_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        # saveメソッドを書かなければ、自動的に入力内容が保存される
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の更新に失敗しました。")
        return super().form_invalid(form)

# 日記を削除するビュー
# DeleteView：指定されたモデルに対して、URL引数pkで受け取った主キーを持つデータを削除するクラス
class DiaryDeleteView(LoginRequiredMixin, OnlyYouMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary_delete.html'
    success_url = reverse_lazy('diary:diary_list')

    # 削除処理を行うメソッド
    def delete(self, request, *args, **kwargs):
        # 対象データを削除してくれる
        # 関連するほかのデータの削除処理記述することもある
        messages.success(self.request, "日記を削除しました。")
        return super().delete(request, *args, **kwargs)

diary/templates/base.html
{# staticファイルを使えるようにする #}
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {# titleという名前のブロックを埋め込む場所 #}
    <title>{% block title %}{% endblock %}</title>
    {# staticフォルダを参照して'assets/favicon.ico'のURLを取得して出力 #}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
    <div id="wrapper">
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
          {# diaryアプリケーションのindexページのURLを取得して表示 #}
          <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'diary:inquiry' %}">INQUIRY</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link {% block active_diary_list %}{% endblock %}"
                     href="{% url 'diary:diary_list' %}">DIARY LIST</a>
              </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
              {# ログインしている場合 #}
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
              </li>
              {# user:ログインしているユーザー #}
              <li style="color:wheat">ようこそ{{user.email}}</li>
              {# ログインしていない場合 #}
              {% else %}
              <li class="nav-item">
                  <a class="nav-link {% block active_signup %}{% endblock %}" href="{% url 'account_signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% block active_login %}{% endblock %}" href="{% url 'account_login' %}">Log In</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      {% block header%}{% endblock %}

      {# メッセージがセットされていた場合 #}
      {% if messages %}
      <div class="container my-div-style">
          <div class="row">
              <ul class="messages" style="list-style: none;">
                  {# セットされている分だけ繰り返す #}
                  {% for message in messages %}
                  <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {# メッセージ本文 #}  
                    {{ message }}
                  </li>
                  {% endfor %}
              </ul>          
          </div>
      </div>
      {% endif %}

      {% block contents%}{% endblock %}

      <!-- Footer -->
      <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Private Dairy 2021</p></div>
      </footer>

      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    </div>
  </body>
</html>

diary/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記作成 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <!-- enctype属性：ファイルをアップロードするフォームに必要 -->
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記削除 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <p>「{{ object.title }}」を本当に削除しますか？</p>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記詳細 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>タイトル</strong>
        </div>
        <div class="col-9">
            {# object：DetailViewで出力された１件のデータ #}
            {{ object.title }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>本文</strong>
        </div>
        <div class="col-9">
            {# |linebreaksbr　改行を<br>タグに置き換える #}
            {{ object.content|linebreaksbr }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>写真</strong>
        </div>
        <div class="col-3">
            {% if object.photo1 %}
            <img src="{{ object.photo1.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo2 %}
            <img src="{{ object.photo2.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo3 %}
            <img src="{{ object.photo3.url }}" width="200" height="200"/>
            {% endif %}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>作成日時</strong>
        </div>
        <div class="col-9">
            {{ object.created_at }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>更新日時</strong>
        </div>
        <div class="col-9">
            {{ object.updated_at }}
        </div>
    </div>

    <a class="btn btn-success mt-5 mb-3" href="{% url 'diary:diary_update' object.pk %}">編集</a>
    <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'diary:diary_delete' object.pk %}">削除</a>
</div>
{% endblock %}

diary/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記一覧 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">新規作成</a>
            </div>
            {# 「モデル名_list」にビューで指定したモデルの全データが格納されている #}
            {% for diary in diary_list %}
            <div class="post-preview">
                {# diary.pk（主キー）をURL引数として渡す #}
                <a href="{% url 'diary:diary_detail' diary.pk %}">
                    <h2 class="post-title">
                        {{ diary.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {# |以降はフィルターを記述 #}
                        {# truncatecharsは文字数を制限する #}
                        {{ diary.content|truncatechars:20 }}
                    </h3>
                    {{diary.photo1}}
                    {% if diary.photo1 %}
                    <img src="{{ diary.photo1.url }}" width="200" height="200"/>
                    {% endif %}
                </a>
                <p class="post-meta">{{ diary.created_at }}</p>
            </div>
            <hr class="my-4">
            {# forでループするデータが０件の時 #}
            {% empty %}
            <p>日記がありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>
            <a class="btn btn-secondary ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/index.html
{# base.htmlをもとにブロックの中身を埋め込む #}
{% extends 'base.html' %}
{% load static %}

{% block title %}Web上にあなた専用の日記ページを保存できるサービス | Private Diary{% endblock %}

{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Private Diary</h1>
      <h2 class="masthead-subheading mb-0">あなた専用の日記保存サービス</h2>
      <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Web Diary</h2>
          <p>Web上で作成/編集/削除ができる日記</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Save Your Diary</h2>
          <p>あなたの日記をWebに保存</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Membership System</h2>
          <p>会員制のWeb日記サービス</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{# base.htmlのリンクのclassにacitveを追加 #}
{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {# formを書く時のおまじない #}
            {% csrf_token %}

            {# 入力内容全体にかかわるエラー #}
            {{ form.non_field_errors }}

            {# form_classで指定した入力フォームを1件ずつ表示 #}
            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    {# labelで指定した内容 #}
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {# inputタグ本体 #}
                {{ field }}

                {# この入力に対するエラー #}
                {{ field.errors }}
            </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/inquiry2.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{# base.htmlのリンクのclassにacitveを追加 #}
{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {# formを書く時のおまじない #}
            {% csrf_token %}

            {# 入力内容全体にかかわるエラー #}
            {{ form.non_field_errors }}

            <div class="mb-4 col-8">
                <label for="id_name" class="form-label">
                    
                    <strong><label for="id_name">お名前:</label></strong>
                </label>
                
                <input type="text" name="name" maxlength="30" class="form-control" placeholder="お名前をここに入力してください。" required id="id_name">

                
                
            </div>
            
            <div class="mb-4 col-8">
                <label for="id_email" class="form-label">
                    
                    <strong><label for="id_email">メールアドレス:</label></strong>
                </label>
                
                <input type="email" name="email" class="form-control" placeholder="メールアドレスをここに入力してください。" required id="id_email">

                
                
            </div>
            
            <div class="mb-4 col-8">
                <label for="id_title" class="form-label">
                    
                    <strong><label for="id_title">タイトル:</label></strong>
                </label>
                
                <input type="text" name="title" maxlength="30" class="form-control" placeholder="タイトルをここに入力してください。" required id="id_title">

                
                
            </div>
            
            <div class="mb-4 col-8">
                <label for="id_message" class="form-label">
                    
                    <strong><label for="id_message">メッセージ:</label></strong>
                </label>
                
                <textarea name="message" cols="40" rows="10" class="form-control" placeholder="メッセージをここに入力してください。" required id="id_message">
</textarea>

                
                
            </div>
            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/inquiry3.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{# base.htmlのリンクのclassにacitveを追加 #}
{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {# formを書く時のおまじない #}
            {% csrf_token %}

            {# 入力内容全体にかかわるエラー #}
            {{ form.non_field_errors }}

            {{ form.as_p }}

            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}