blog/urls.py
from django.urls import path

from . import views

# アプリケーション名
app_name = 'blog'
urlpatterns = [
    # blog/''にアクセスされたらviews.pyのIndexViewを実行
    # ページ名はindex
    path('', views.IndexView.as_view(), name="index"),
    # blog/'post'にアクセスされたらviews.pyのPostViewを実行
    # ページ名はpost
    path('post', views.PostView.as_view(), name="post"),

    path('blog-list/', views.BlogListView.as_view(), name="blog_list"),
]

private_diary/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    # ""にアクセスされたら、diary.urlsに振り分ける
    path("", include('diary.urls')),
    # "blog/"にアクセスされたら、diary.urlsに振り分ける
    path("blog/", include('blog.urls')),

    # "accounts/"にアクセスされたら、allauthの認証ページに振り分ける
    # ルーティング内容はP227を参照
    path("accounts/", include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL,
    document_root=settings_dev.MEDIA_ROOT)

blog/models.py
from django.db import models

from accounts.models import CustomUser

# Create your models here.

class Blog(models.Model):
    
    # 必要な項目を列挙する
    # ユーザー：外部キー（カスタムユーザー）
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    # タイトル：文字列　最大40文字
    title = models.CharField(verbose_name='タイトル', max_length=40)
    # 本文：テキスト　空白許可
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    # 写真：画像　空白許可
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    # 作成日時：日付時刻　新規作成時、自動で現在時刻を設定
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    # 更新日時：日付時刻　更新時、自動で現在時刻を設定
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'ブログ'

blog/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField(label='タイトル', max_length=30)
    # sexの選択肢
    _choices=(
        # 送信する値と表示する文字列を組で記述する
        (1,'男性'),
        (2,'女性'),
        (3,'未回答')
    )
    # ChoiceField:デフォルトはセレクトボックス
    # widget=forms.RadioSelectでラジオボタン
    sex = forms.ChoiceField(label='性別', choices=_choices, widget=forms.RadioSelect)

    # MultipleChoiceFieldは複数選択
    # widget=forms.CheckboxSelectMultipleでチェックボックス
    sex2 = forms.MultipleChoiceField(label='性別', choices=_choices,widget=forms.CheckboxSelectMultiple)

    email1 = forms.EmailField(label='メールアドレス')
    email2 = forms.EmailField(label='メールアドレス(再入力)')

    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'


        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    # clean_フィールド名　メソッド
    # 該当フィールドの入力値チェックを行う
    def clean_message(self):
        # 入力されたmessageの値を取得
        message = self.cleaned_data['message']
        if("NG" in message):
            # エラーを発生させる
            # 引数が画面上にエラーメッセージとして表示される
            raise forms.ValidationError('NGワードが含まれています')
        return message

    # 複数のフィールドに対するチェックを行う
    def clean(self):
        cleaned_data=super().clean()
        # 入力された値を取得
        email1=cleaned_data.get('email1')
        email2=cleaned_data.get('email2')
        if email1 != email2:
            # form.non_field_errorsで表示される
            raise forms.ValidationError('メールアドレスが一致しません')

            # email2にエラーメッセージを表示させたい場合は
            # raise~の代わりに下記を記載
            # self.add_error('email2','メールアドレスが一致しません')

blog/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib import messages

import logging
logger = logging.getLogger(__name__)

# 同じフォルダのforms.pyからPostFormクラスをインポート
from .forms import PostForm

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Blog

# Create your views here.

class IndexView(generic.TemplateView):
    # templatesフォルダの中のblog/index.htmlを表示
    template_name='blog/index.html'

class PostView(generic.FormView):
    # templatesフォルダの中のblog/input.htmlを表示
    template_name='blog/post.html'
    form_class=PostForm
    success_url=reverse_lazy('blog:post')
    
    def form_valid(self, form):
        
        # POST送信されたnextの値を取得
        next = self.request.POST.get('next')
        # テンプレートで出力したい変数
        context={'form':form, 'tekitou':'適当な文字列'}

        # 確認画面の表示
        if next == 'check':
            # check.htmlを表示
            # contextの内容をテンプレートに渡す
            return render(self.request,'blog/check.html',context)
        # 入力画面に戻る
        elif next=='back':
            # post.htmlを表示
            return render(self.request,'blog/post.html',context)
        # 確定する
        elif next=='confirm':
            # 本来の成功時の処理を記述
            # form.send_email()
            messages.success(self.request, 'メッセージを送信しました。')
            logger.info('Inquiry sent by {}'.format(form.cleaned_data['email1']))
            print("aaaaaaaaaaaaaaaaaaa")
            return super().form_valid(form)

class BlogListView(LoginRequiredMixin, generic.ListView):
    model = Blog
    template_name='blog/blog_list.html'

    def get_queryset(self):
        blogs = Blog.objects.filter(user=self.request.user).order_by('-created_at')
        return blogs

blog/templates/blog/base.html
{# staticファイルを使えるようにする #}
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {# titleという名前のブロックを埋め込む場所 #}
    <title>{% block title %}{% endblock %}</title>
    {# staticフォルダを参照して'assets/favicon.ico'のURLを取得して出力 #}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
    <div id="wrapper">
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
          {# blogアプリケーションのindexページのURLを取得して表示 #}
          <a class="navbar-brand" href="{% url 'blog:index' %}">PRIVATE DIARY</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'blog:post' %}">INQUIRY</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link {% block active_diary_list %}{% endblock %}"
                     href="{% url 'blog:blog_list' %}">BLOG LIST</a>
              </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="#">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Log In</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block header%}{% endblock %}

      {# メッセージがセットされていた場合 #}
      {% if messages %}
      <div class="container my-div-style">
          <div class="row">
              <ul class="messages" style="list-style: none;">
                  {# セットされている分だけ繰り返す #}
                  {% for message in messages %}
                  <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {# メッセージ本文 #}  
                    {{ message }}
                  </li>
                  {% endfor %}
              </ul>          
          </div>
      </div>
      {% endif %}

      {% block contents%}{% endblock %}

      <!-- Footer -->
      <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Private Dairy 2021</p></div>
      </footer>

      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    </div>
  </body>
</html>

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}ブログ一覧 | Private Blog{% endblock %}

{% block active_blog_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="">新規作成</a>
            </div>
            {# 「モデル名_list」にビューで指定したモデルの全データが格納されている #}
            {% for blog in blog_list %}
            <div class="post-preview">
                {# blog.pk（主キー）をURL引数として渡す #}
                <a href="">
                    <h2 class="post-title">
                        {{ blog.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {# |以降はフィルターを記述 #}
                        {# truncatecharsは文字数を制限する #}
                        {{ blog.content|truncatechars:20 }}
                    </h3>
                    {{blog.photo1}}
                    {% if blog.photo1 %}
                    <img src="{{ blog.photo1.url }}" width="200" height="200"/>
                    {% endif %}
                </a>
                <p class="post-meta">{{ blog.created_at }}</p>
            </div>
            <hr class="my-4">
            {# forでループするデータが０件の時 #}
            {% empty %}
            <p>ブログがありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/check.html
{% extends 'blog/base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <p>下記内容でいいですか？</p>
        {{ tekitou }}
        {% for field in form %}
        <div class="mb-4 col-8">
            <label for="{{ field.id_for_label }}" class="form-label">
                <strong>{{ field.label_tag }}</strong>
            </label>
            {{ field.value }}
        </div>
        {% endfor %}
        <form method="post">
            {% csrf_token %}

            {% for field in form %}
                {# <input type="hidden">として出力 #}
                {{field.as_hidden}}
            {% endfor %}
            <button class="ui button grey" type="submit" name="next" value="back">戻る</button>
            <button class="ui button orange" type="submit" name="next" value="confirm">確定</button>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{# base.htmlをもとにブロックの中身を埋め込む #}
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Web上にあなた専用のブログを保存できるサービス | Private Blog{% endblock %}

{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Private Blog</h1>
      <h2 class="masthead-subheading mb-0">あなた専用のブログ保存サービス</h2>
      <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Web Diary</h2>
          <p>Web上で作成/編集/削除ができる日記</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Save Your Diary</h2>
          <p>あなたの日記をWebに保存</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Membership System</h2>
          <p>会員制のWeb日記サービス</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{# base.htmlのリンクのclassにacitveを追加 #}
{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {# formを書く時のおまじない #}
            {% csrf_token %}

            {# 入力内容全体にかかわるエラー #}
            {{ form.non_field_errors }}

            {# form_classで指定した入力フォームを1件ずつ表示 #}
            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    {# labelで指定した内容 #}
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {# inputタグ本体 #}
                {{ field }}

                {# この入力に対するエラー #}
                {{ field.errors }}
            </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit" name="next" value="check">送信</button>
        </form>
    </div>
</div>
{% endblock %}